# Generated by Django 2.0.3 on 2018-03-28 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='company_percentage_change',
            new_name='company_ticker_name',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='company_trade_price',
        ),
    ]
