# Generated by Django 2.0.3 on 2018-04-01 05:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockData', '0002_auto_20180328_2338'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together={('stockholder', 'company_ticker_name'), ('stockholder', 'company_name')},
        ),
    ]
